# Assignment 2 Genrate Text using RNN

Import some useful librariers and dataset from local drive

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import RNN, SimpleRNNCell, Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical
with open("/content/drive/MyDrive/myfile.txt") as myfile:
    mytext = myfile.read()

After import the text data...reviewing it with mytext statement

In [ ]:
mytext


'The Uttarakhand Police said Saturday that they had arrested Abdul Malik who allegedly led the violent protests in Haldwani on February 8 in which four persons were killed.\n\nSpeaking to The Indian Express, Inspector General and Police Headquarters spokesperson Nilesh Anand Bharne said Malik was arrested by Uttarakhand Police from New Delhi. His was the 79th arrest in the case.\n\nViolence erupted in Nainital district’s Haldwani on February 8 after the administration conducted a drive during which a mosque and a madrasa were demolished in Banbhoolpura area. District authorities said both structures stood on Nazool land — government land not officially mentioned in revenue records. As stones were pelted, cars torched and the local police station surrounded by a mob, Chief Minister Pushkar Singh Dhami had called for shoot-at-sight orders\nHe said that on Saturday morning, they moved the First Additional District Judge (ADJ) court in Haldwani for anticipatory bail, but now, with Malik’s 

Perform tokenization on given data set

In [ ]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [ ]:
mytokenizer.word_index

{'the': 1,
 'in': 2,
 'a': 3,
 'to': 4,
 'and': 5,
 'police': 6,
 'said': 7,
 'for': 8,
 'of': 9,
 'that': 10,
 'malik': 11,
 'were': 12,
 'was': 13,
 'on': 14,
 'violence': 15,
 'they': 16,
 'haldwani': 17,
 'by': 18,
 'property': 19,
 'had': 20,
 'february': 21,
 '8': 22,
 'he': 23,
 'court': 24,
 'with': 25,
 'uttarakhand': 26,
 'four': 27,
 'during': 28,
 'district': 29,
 'land': 30,
 'government': 31,
 'as': 32,
 'station': 33,
 'at': 34,
 'bail': 35,
 'malik’s': 36,
 'registered': 37,
 'her': 38,
 'illegal': 39,
 'saturday': 40,
 'arrested': 41,
 'allegedly': 42,
 'led': 43,
 'protests': 44,
 'which': 45,
 'indian': 46,
 'his': 47,
 'arrest': 48,
 'nainital': 49,
 'after': 50,
 'administration': 51,
 'drive': 52,
 'demolished': 53,
 'structures': 54,
 'nazool': 55,
 'not': 56,
 'chief': 57,
 'minister': 58,
 'dhami': 59,
 'under': 60,
 'rioting': 61,
 'public': 62,
 'damage': 63,
 'bahuguna': 64,
 'day': 65,
 'also': 66,
 'against': 67,
 'wife': 68,
 'safia': 69,
 'it': 70,
 'dir

# Now we can pre process the data

In [ ]:
my_input_sequences = []
for line in mytext.split('\n'):
    token_list = mytokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [ ]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [ ]:
input_sequences[10]


array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 26,  6,  7,
       40, 10, 16, 20, 41, 74, 11, 75], dtype=int32)

In [ ]:
x = input_sequences[:, :-3]
y = input_sequences[:, -3]

In [ ]:
x[4]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1, 26,  6], dtype=int32)

In [ ]:
y

array([  0,   1,  26,   6,   7,  40,  10,  16,  20,  41,  74,  11,  75,
        42,  43,   1,  76,  44,   2,  17,  14,  21,  22,   2,  45,  27,
        77,   0,  79,   4,   1,  46,  80,  81,  82,   5,   6,  83,  84,
        85,  86,  87,   7,  11,  13,  41,  18,  26,   6,  88,  89,  90,
        47,  13,   1,  91,  48,   2,   0,  15,  93,   2,  49,  94,  17,
        14,  21,  22,  50,   1,  51,  95,   3,  52,  28,  45,   3,  96,
         5,   3,  97,  12,  53,   2,  98,  99,  29, 100,   7, 101,  54,
       102,  14,  55,  30, 103,  31,  30,  56, 104, 105,   2, 106, 107,
        32, 108,  12, 109, 110, 111,   5,   1, 112,   6,  33, 113,  18,
         3, 114,  57,  58, 115, 116,  59,  20, 117,   8, 118,  34,   0,
        23,   7,  10,  14,  40, 121,  16, 122,   1, 123, 124,  29, 125,
       126,  24,   2,  17,   8, 127,  35, 128, 129,  25,  36,  48,  16,
       130, 131,   3, 132,  24,   8,   0, 134, 135,  12,  37,   2, 136,
        25,   1,  15, 137, 138,   8,   1, 139,  14,   1,   6,  3

In [ ]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [ ]:
y[8]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

# After pre proccessing, build and train the model respectively.

In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 75, 100)           27400     
                                                                 
 lstm (LSTM)                 (None, 100)               80400     
                                                                 
 dense (Dense)               (None, 274)               27674     
                                                                 
Total params: 135474 (529.20 KB)
Trainable params: 135474 (529.20 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(RNN(SimpleRNNCell(100)))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 75, 100)           27400     
                                                                 
 rnn (RNN)                   (None, 100)               20100     
                                                                 
 dense_1 (Dense)             (None, 274)               27674     
                                                                 
Total params: 75174 (293.65 KB)
Trainable params: 75174 (293.65 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=50, verbose=1)

Epoch 1/50


ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1150, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_1" is incompatible with the layer: expected shape=(None, 75), found shape=(None, 73)


# Here we analyse our build model and accurecy.

In [ ]:
import numpy as np
from keras.preprocessing.sequence import pad_sequences

input_text = "Malik’s wife"
predict_next_words = 4


for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)


1/1 [==============================] - 0s 54ms/step
Malik’s wife said 147 minister district
